import CreateTask from "@/components/CreateTask/CreateTask";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import TasksContainer from "@/components/TasksContainer/TasksContainer";
import styles from "@/styles/Home.module.css";
import { Box } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { getTasks } from "services/services";
import { HomePageProps } from "type";

const Home: NextPage<HomePageProps> = ({ tasks }) => {
  const [userTasks, setUserTasks] = useState(tasks);

  return (
    <>
      <Header />
      <div className={styles.container}>
        <Head>
          <title>Task List</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>
          <CreateTask tasks={userTasks} setUserTasks={setUserTasks} />
          <Box sx={{ display: "flex" }}>
            <TasksContainer
              tasks={userTasks}
              setUserTasks={setUserTasks}
              stateToShow="ToDo"
            />
            <TasksContainer
              tasks={userTasks}
              setUserTasks={setUserTasks}
              stateToShow="InProgress"
            />
            <TasksContainer
              tasks={userTasks}
              setUserTasks={setUserTasks}
              stateToShow="Done"
            />
          </Box>
        </main>
      </div>
      <Footer />
    </>
  );
};
export default Home;

export const getServerSideProps = async () => {
  const newTasks = getTasks();

  return {
    props: {
      tasks: await newTasks,
    },
  };
};
